services:

  python:
    image: python:3.10
    tty: true
    links:
      - postgres
    networks:
      - db
    volumes:
      - .:/usr/flask-postgres
    working_dir: /usr/flask-postgres
    command:
      - "/bin/bash"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    tty: true
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    networks:
      - db
    ports:
      - "5051:5050"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin


networks:
  db:
    driver: bridge


volumes:
  postgres: {}
  pgadmin: {}
